# -*- coding: utf-8 -*-
"""Day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xTVPnAvJEHVfsaOmwW3MbSc6rk5NaxC6
"""

name = input("Enter your name: ")
age = int(input("Enter your age: "))
marks1 = int(input("Enter marks S1: "))
marks2 = int(input("Enter marks S2: "))
marks3 = int(input("Enter marks S3: "))

print("Name:", name)
print("Age:", age)
print("Marks for subject 1:", marks1)
print("Marks for subject 2:", marks2)
print("Marks for subject 3:", marks3)

total_marks = marks1 + marks2 + marks3
average_marks = total_marks / 3

print("Total Marks:",total_marks)
print("Average Marks",average_marks)

if marks1 >= 40 and marks2 >= 40 and marks3 >= 40:
    print("\nStudent scored 40+ in every subject.")
else:
    print("\nStudent did NOT score 40+ in every subject.")



score=int(input("enter score:"))
if score>=90:
  print("grade A")
elif score>=80:
  print("grade c")
else:
  print("fail")

num=int(input("enter the number:"))
if num%3==0 and num%5==0:
  print("FizzBuzz")
elif num%5==0:
  print("Buzz")
elif num%3==0:
  print("Fizz")

#prime number
num= int(input("enter number:"))
for i in range(2,num):
  if num%i==0:
    print("not a prime number")
    break
else:
  print("prime number")

for i in range(1,6):
  if i==3:
    continue
  print(i)

n = int(input("Enter a number (N): "))

sum_even = 0
sum_odd = 0

for i in range(1, n + 1):
    if i % 2 == 0:
        sum_even += i
    else:
        sum_odd += i

print(f"Sum of even numbers up to {n}: {sum_even}")
print(f"Sum of odd numbers up to {n}: {sum_odd}")

#factorial of a number
num=int(input("enter number:"))
fact=1
for i in range(1,num+1):
  fact=fact*i
print(fact)

#LISTS
fruits=["apple","banana","mango","orange"]
print(fruits)
print(len(fruits))

fruits.append("grapes")
more_fruits=["pineapple","cherry"]
fruits.extend(more_fruits)
print("after extend:",fruits)

print("first fruit:",fruits[0])
print("last fruit:",fruits[-1])
print(fruits[2:5])

fruits[1]="strawberry"
print("after upddating index 1:", fruits)
fruits.remove("mango")
print("after remove mango:",fruits)

remove_fruit=fruits.pop(2)
print(removed_fruits)
print("after pop", fruits)

fruits.sort()
print("after sort:", fruits)
fruits.reverse()
print("after reverse:".fruits)

fruits.clear()
print(fruits)

#TUPLE
single_item_tuple=(42,)
print(single_item_tuple)



#tuple to list
t=(1,2,3)
l=list(t)
l.append(4)
t=tuple(l)
print(t)

#tuple unpacking

coordintes=(40.7128, -74.0060)
latitude,longitude=coordinates
print("ununpacked-latitude:",latitude,"longitude:",longitude)

#the * means rest of the items
a,b,*c=(1,2,3,4,5)
print("extended unpacking-first", a, "second:",b,"Rest:",c)

#Dictionary